# Generated by Django 4.1.3 on 2023-01-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(max_length=50)),
                ('receptor', models.CharField(max_length=50)),
                ('cuerpo', models.CharField(max_length=2000)),
                ('status', models.CharField(max_length=50)),
                ('fecha_de_envio', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
