# Generated by Django 4.1.3 on 2023-01-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_Turno', models.CharField(max_length=50)),
                ('Barbero', models.CharField(max_length=50)),
                ('Cliente', models.CharField(max_length=50)),
                ('fecha_turno', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
