# Generated by Django 4.1.3 on 2022-12-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMiembro', '0003_remove_miembro_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='fecha_nacimiento',
            field=models.DateField(auto_now=True),
        ),
    ]
