# Generated by Django 4.1.3 on 2022-12-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMiembro', '0005_alter_miembro_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
