# Generated by Django 4.1.3 on 2022-12-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMiembro', '0006_alter_miembro_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.IntegerField()),
                ('Cargo', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
