# Generated by Django 4.1.3 on 2022-12-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMiembro', '0007_colaborador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='Cargo',
            new_name='cargo',
        ),
    ]
