# Generated by Django 4.1.3 on 2022-12-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMiembro', '0008_rename_cargo_colaborador_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('codigo', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
