# Generated by Django 4.1.3 on 2022-12-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMiembro', '0009_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
