# Generated by Django 4.1.3 on 2023-01-22 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMiembro', '0012_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barbero', models.CharField(max_length=50)),
                ('servicio', models.CharField(max_length=50)),
                ('servicio_cant', models.IntegerField()),
                ('producto', models.CharField(max_length=50)),
                ('producto_cant', models.IntegerField()),
                ('fecha_registro', models.DateField(blank=True, default=datetime.datetime(2023, 1, 22, 10, 55, 26, 558066), null=True)),
            ],
        ),
    ]
