# Generated by Django 4.1.3 on 2023-01-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMiembro', '0014_alter_ventas_fecha_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='fecha_registro',
        ),
    ]
