# Generated by Django 4.1.3 on 2023-01-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMiembro', '0016_ventas_fecha_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo')),
                ('contenido', models.CharField(max_length=1000, verbose_name='contenido')),
                ('fecha_de_posteo', models.DateTimeField(verbose_name='fecha_de_posteo')),
            ],
        ),
    ]
