# Generated by Django 4.1.3 on 2023-01-28 15:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMiembro', '0022_alter_post_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo')),
                ('contenido', ckeditor.fields.RichTextField(blank=True)),
                ('fecha_de_posteo', models.DateTimeField(verbose_name='fecha_de_posteo')),
            ],
        ),
    ]
