# Generated by Django 4.1.3 on 2023-01-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMiembro', '0023_posteo'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
