# Generated by Django 4.1.3 on 2023-01-28 16:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMiembro', '0024_posteo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
