# Generated by Django 4.1.3 on 2023-01-28 21:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMiembro', '0025_alter_posteo_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creador',
            field=models.CharField(default=-3, max_length=100, verbose_name='titulo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
